on:
  push:
    branches:
      - master
    # Sequence of patterns matched against refs/tags
    #tags:
    #  - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name : GITHUB CONTEXT
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: |
          echo "$GITHUB_EVENT"
          echo "${{ github.ref }}"
      - name: Create Release
        id: create_release
        if: ${{ false }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
     git     tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ join( github.event.commits.*.message, "\n" }}
          draft: false
          prerelease: false
